### ISSUE TITLE
.bin/tsb broken

### ISSUE THREAD

**Issue by heycalmdown** [TypeScriptBuilder/tsb#33]
1.0.1 installed by npm has broken by following carrage return with hash bang.

It is known issue of npm with Windows. https://github.com/npm/npm/issues/2097
Sound familiar?

```bash
$ tsb
env: node\r: No such file or directory
heyPro:edge-ui kson$ tsb
env: node\r: No such file or directory
heyPro:edge-ui kson$ tsb .
env: node\r: No such file or directory
heyPro:edge-ui kson$ tsb -v
env: node\r: No such file or directory
```

**Comment by basarat** [comment]
Thanks for testing and reporting the bug :rose: Will investigate.

Note : the NPM version is mostly for camping at the moment. See Readme : https://github.com/TypeScriptBuilder/tsb/tree/master#usage you need to setup manually ... and its not ready (planned release is January)

**Comment by heycalmdown** [comment]
Okay, thanks.

**Comment by basarat** [comment]
Planned workaround. Have a simple *non compiled* `tsb.js` file that has the right line endings and just requires our binary.

**Comment by basarat** [comment]
@heycalmdown should be fixed now as I've setup automatic NPM deployment that happens from a unix version of git https://github.com/TypeScriptBuilder/tsb/blob/master/docs/contributing/DEPLOYMENT.md :rose:

**Comment by heycalmdown** [comment]
Thanks, it works!

**Comment by basarat** [comment]
Thanks for testing :rose: We should have session support soon so it will remember open tabs and stuff (and not used my hardcoded tabs). Nevertheless *January* :smile:
