### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by heycalmdown** [TypeScriptBuilder/tsb#36]
We have missing dependencies to launch

* http-proxy
* webpack
* webpack-dev-server

to run

* style-loader
* css-loader

**Comment by basarat** [comment]
These dependencies are *dev only* (not relevant after npm publish). I've clarified what we mean by that : https://github.com/TypeScriptBuilder/tsb/blob/master/docs/contributing/README.md#webpack 

If you are thinking of setting up a local dev environment, these should come down as a part of `npm install` : https://github.com/TypeScriptBuilder/tsb/blob/master/docs/contributing/README.md#setup Is that not the case? Or are these files getting requested when this package is used from npm? Thanks :rose:

**Comment by basarat** [comment]
> Or are these files getting requested when this package is used from npm

That seems to be the case : 

![image](https://cloud.githubusercontent.com/assets/874898/10934239/c8a7df04-8332-11e5-8d49-14262ffbbbba.png)

Investigating :rose:

**Comment by basarat** [comment]
Released : https://github.com/TypeScriptBuilder/tsb/releases/tag/v1.0.5

**Comment by heycalmdown** [comment]
Does work as well
Thanks!
