### ISSUE TITLE
Error when navigating to tsb in browser

### ISSUE THREAD

**Issue by Burgov** [TypeScriptBuilder/tsb#50]
`Uncaught TypeError: item.commandName.split is not a function`

![image](https://cloud.githubusercontent.com/assets/417674/11658968/1a8971cc-9dc6-11e5-9c23-d73bcfb0f4bc.png)

As you can see, Ctrl+/ maps to a function, rather than a string

Trace:
```
addEditorMapToCommands	@	commands.js:325
(anonymous function)	@	commands.js:336
(anonymous function)	@	bundle.js:2129
__webpack_require__	@	bundle.js:521
fn	@	bundle.js:76
(anonymous function)	@	ui.js:13
(anonymous function)	@	bundle.js:1955
__webpack_require__	@	bundle.js:521
fn	@	bundle.js:76
(anonymous function)	@	root.js:17
(anonymous function)	@	bundle.js:1013
__webpack_require__	@	bundle.js:521
fn	@	bundle.js:76
(anonymous function)	@	main.js:2
(anonymous function)	@	bundle.js:1007
__webpack_require__	@	bundle.js:521
fn	@	bundle.js:76
(anonymous function)	@	multi_main:3
(anonymous function)	@	bundle.js:551
__webpack_require__	@	bundle.js:521
(anonymous function)	@	bundle.js:544
(anonymous function)	@	bundle.js:547
```

The problem appears when it tries to add the sublimeMap

If you need any more info, let me know

**Comment by Burgov** [comment]
seems to be related to this commit:

https://github.com/codemirror/CodeMirror/commit/8a012c0ae93654c911e029f82f92d5e21c1f389d

**Comment by basarat** [comment]
Yup. I have 5.7.0. Investigating a fix :rose:
